// src/admin/pages/ThoughtManager.vue
<script setup lang="ts">
import { ref, onMounted, inject } from 'vue';
import { request } from '../lib/api';
import { useDialog } from '../hooks/useDialog';
import { formatDateTime } from '../lib/utils';
type UseDialogType = ReturnType<typeof useDialog>;

// 注入全局对话框功能
const dialog = inject<UseDialogType>('dialog');
if (!dialog) {
    throw new Error('Dialog service not provided');
}

import { useImageUpload } from '../hooks/useImageUpload';
import { IconTrash, IconPen, IconImage } from '../components/Icons';
import { marked } from 'marked';

interface Thought {
    id?: number;
    content: string;
    mood: string;
    likes?: number;
    created_at?: string;
}

const thoughts = ref<Thought[]>([]);
const content = ref('');
const textareaRef = ref<HTMLTextAreaElement | null>(null); // 获取 textarea 实例
const fileInputRef = ref<HTMLInputElement | null>(null);   // 获取 file input 实例
// Hook
const { isUploading, uploadFile, handlePaste, handleDrop, insertAtCursor } = useImageUpload(dialog);

const mood = ref('happy');
// 🟢 新增编辑状态
const editingId = ref<number | null>(null);

const moodMap: Record<string, string> = {
    neutral: '😐 平静',
    happy: '😄 愉快',
    pensive: '🤔 沉思',
    excited: '🤩 兴奋'
};

const formatDate = (dateStr?: string) => {
    if (!dateStr) return '';
    return formatDateTime(dateStr);
};

const loadThoughts = async () => {
    const data = await request<Thought[]>('/api/thoughts');
    if (data) thoughts.value = data;
};

// 🟢 点击编辑按钮
const handleEdit = (thought: Thought) => {
    content.value = thought.content;
    mood.value = thought.mood;
    editingId.value = thought.id || null;
};

// 🟢 取消编辑
const cancelEdit = () => {
    content.value = '';
    mood.value = 'neutral';
    editingId.value = null;
};

// 🟢 提交逻辑 (提取出来方便快捷键调用)
const handleSubmit = async () => {
    if (!content.value || isUploading.value) return; // 上传中禁止提交

    const res = await request<{ success: boolean }>('/api/thought', 'POST', {
        id: editingId.value,
        content: content.value,
        mood: mood.value
    });

    if (res?.success) {
        content.value = '';
        mood.value = 'neutral';
        editingId.value = null;
        loadThoughts();
    }
};

// 🟢 快捷键处理
const handleKeydown = (e: KeyboardEvent) => {
    // MetaKey 是 Mac 的 Command 键，CtrlKey 是 Windows 的 Ctrl
    if ((e.metaKey || e.ctrlKey) && e.key === 'Enter') {
        e.preventDefault();
        handleSubmit();
    }
};

// 🟢 按钮选择文件上传
const onFileSelect = async (e: Event) => {
    const input = e.target as HTMLInputElement;
    if (input.files && input.files[0] && textareaRef.value) {
        const url = await uploadFile(input.files[0]);
        if (url) {
            insertAtCursor(textareaRef.value, `![](${url})`, (val) => content.value = val);
        }
        input.value = ''; // 清空，允许重复选同一张
    }
};

// 粘贴和拖拽的包装函数
const onPaste = (e: ClipboardEvent) => {
    if (textareaRef.value) handlePaste(e, textareaRef.value, (val) => content.value = val);
};
const onDrop = (e: DragEvent) => {
    if (textareaRef.value) handleDrop(e, textareaRef.value, (val) => content.value = val);
};

const handleDelete = async (id: number) => {
    const confirmed = await dialog.confirm({
        message: '删除?',
        title: '删除确认'
    });
    if (!confirmed) return;
    await request(`/api/thought/${id}`, 'DELETE');
    // 如果正在编辑的被删了，也要重置
    if (editingId.value === id) cancelEdit();
    loadThoughts();
};

function toHtml(content: string) {
    return marked.parse(content) || '';
}

onMounted(loadThoughts);
</script>
<template>
    <div class="grid grid-cols-1 md:grid-cols-3 gap-6 h-full">
        <div class="md:col-span-1 space-y-4">
            <div class="bg-white p-4 rounded-xl shadow-sm border border-slate-200"
                :class="{ 'ring-2 ring-blue-100': editingId }">

                <textarea ref="textareaRef" v-model="content" @keydown="handleKeydown" @paste="onPaste" @drop="onDrop"
                    @dragover.prevent
                    class="w-full h-32 p-3 border border-slate-200 rounded resize-none focus:ring-2 focus:ring-blue-500 outline-none mb-3"
                    placeholder="此刻你在想什么... (Cmd+Enter 发布，支持粘贴/拖拽图片)"></textarea>

                <div class="flex justify-between items-center">
                    <div class="flex gap-2">
                        <select v-model="mood" class="p-2 border border-slate-200 rounded text-sm bg-white">
                            <option v-for="(label, key) in moodMap" :key="key" :value="key">{{ label }}</option>
                        </select>

                        <button @click="fileInputRef?.click()" class="p-2 text-slate-500 hover:bg-slate-100 rounded"
                            title="上传图片">
                            <IconImage class="w-5 h-5" />
                        </button>
                        <input ref="fileInputRef" type="file" accept="image/*" class="hidden" @change="onFileSelect" />
                    </div>

                    <button @click="handleSubmit" :disabled="!content || isUploading"
                        class="px-4 py-2 bg-slate-900 text-white rounded text-sm hover:bg-slate-700 disabled:opacity-50 transition-colors"
                        :class="{ 'bg-blue-600 hover:bg-blue-700': editingId }">
                        {{ isUploading ? '上传中...' : (editingId ? '更新' : '发布') }}
                    </button>
                </div>
            </div>
        </div>


        <div class="md:col-span-2 overflow-y-auto pr-0 md:pr-2">
            <h2 class="text-xl font-bold mb-4 text-slate-500">历史记录 ({{ thoughts.length }})</h2>
            <div class="space-y-4">
                <div v-for="thought in thoughts" :key="thought.id"
                    class="bg-white p-4 rounded-xl shadow-sm border border-slate-100 group relative transition-colors"
                    :class="{ 'border-blue-300 bg-blue-50/30': editingId === thought.id }">
                    <div
                        class="absolute top-4 right-4 opacity-100 md:opacity-0 group-hover:opacity-100 transition-opacity flex gap-2">
                        <button @click="handleEdit(thought)"
                            class="text-blue-500 hover:text-blue-700 bg-blue-50 p-1 rounded" title="编辑">
                            <IconPen class="w-4 h-4" />
                        </button>
                        <button @click="handleDelete(thought.id!)"
                            class="text-red-400 hover:text-red-600 bg-red-50 p-1 rounded" title="删除">
                            <IconTrash class="w-4 h-4" />
                        </button>
                    </div>

                    <div class="prose prose-sm mb-2 text-slate-800 font-serif whitespace-pre-wrap"
                        v-html="toHtml(thought.content)">

                    </div>

                    <div class="flex items-center gap-4 text-xs text-slate-400 font-mono">
                        <div class="flex items-center gap-1">
                            <span>{{ formatDate(thought.created_at) }}</span>
                            <span class="bg-slate-100 px-1.5 py-0.5 rounded text-slate-500">
                                {{ moodMap[thought.mood]?.split(' ')[0] }}
                            </span>
                        </div>
                        <div class="flex items-center gap-1 text-pink-400">
                            <span>❤️</span>
                            <span>{{ thought.likes || 0 }}</span>
                        </div>
                        <span v-if="editingId === thought.id" class="text-blue-500 font-bold">正在编辑...</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
</template>

// admin/src/components/ThoughtManager.tsx
// src/components/ThoughtManager.tsx
import React, { useState, useEffect } from 'react';
import type { Thought } from '../types';
import { request } from '../lib/api';
import { IconTrash } from './Icons';

export const ThoughtManager: React.FC = () => {
    const [thoughts, setThoughts] = useState<Thought[]>([]);
    const [content, setContent] = useState('');
    const [mood, setMood] = useState<Thought['mood']>('neutral');

    useEffect(() => {
        loadThoughts();
    }, []);

    const loadThoughts = async () => {
        const data = await request<Thought[]>('/api/thoughts');
        if (data) setThoughts(data);
    };

    const handleSubmit = async () => {
        if (!content) return;
        const res = await request<{ success: boolean }>('/api/thought', 'POST', { content, mood });
        if (res?.success) {
            setContent('');
            setMood('neutral');
            loadThoughts();
        }
    };

    const handleDelete = async (id: number) => {
        if (!confirm('删除此条随笔?')) return;
        // 注意：后端 API 路径是 /api/thought/:id
        await request(`/api/thought/${id}`, 'DELETE');
        loadThoughts();
    };

    const moodEmoji = {
        neutral: '😐 平静',
        happy: '😄 愉快',
        pensive: '🤔 沉思',
        excited: '🤩 兴奋'
    };

    return (
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6 h-full">
            {/* 左侧：发布框 */}
            <div className="md:col-span-1 space-y-4">
                <h2 className="text-2xl font-serif font-bold mb-4">记录想法</h2>
                <div className="bg-white p-4 rounded-xl shadow-sm border border-slate-200">
                    <textarea
                        className="w-full h-32 p-3 border border-slate-200 rounded resize-none focus:ring-2 focus:ring-blue-500 outline-none mb-3"
                        placeholder="此刻你在想什么..."
                        value={content}
                        onChange={e => setContent(e.target.value)}
                    />
                    <div className="flex justify-between items-center">
                        <select
                            className="p-2 border border-slate-200 rounded text-sm bg-white"
                            value={mood}
                            onChange={(e: any) => setMood(e.target.value)}
                        >
                            {Object.entries(moodEmoji).map(([k, v]) => (
                                <option key={k} value={k}>{v}</option>
                            ))}
                        </select>
                        <button
                            onClick={handleSubmit}
                            disabled={!content}
                            className="px-4 py-2 bg-slate-900 text-white rounded text-sm hover:bg-slate-700 disabled:opacity-50"
                        >
                            发布
                        </button>
                    </div>
                </div>
            </div>

            {/* 右侧：列表 */}
            <div className="md:col-span-2 overflow-y-auto pr-2">
                <h2 className="text-xl font-bold mb-4 text-slate-500">历史记录 ({thoughts.length})</h2>
                <div className="space-y-4">
                    {thoughts.map(thought => (
                        <div key={thought.id} className="bg-white p-4 rounded-xl shadow-sm border border-slate-100 group relative">
                            <div className="absolute top-4 right-4 opacity-0 group-hover:opacity-100 transition-opacity">
                                <button onClick={() => handleDelete(thought.id!)} className="text-red-400 hover:text-red-600">
                                    <IconTrash className="w-4 h-4" />
                                </button>
                            </div>

                            <div className="prose prose-sm mb-2 text-slate-800 font-serif">
                                {thought.content}
                            </div>

                            <div className="flex items-center gap-2 text-xs text-slate-400 font-mono">
                                <span>{new Date(thought.created_at!).toLocaleString()}</span>
                                <span className="bg-slate-100 px-1.5 py-0.5 rounded text-slate-500">
                                    {moodEmoji[thought.mood].split(' ')[0]}
                                </span>
                            </div>
                        </div>
                    ))}
                </div>
            </div>
        </div>
    );
};
